version: '3.8'
services:
  app-workshop:
    image: ghcr.io/pooneyy/1panel-app-workshop:latest
    container_name: app-workshop
    ports:
      - 8080:80
    restart: unless-stopped
    pull_policy: always
